DZ_13.Working with Python classes and functions
Ruslan080183/Training pull request #11
Opened 2022-12-10 14:09 UTC by Ruslan080183

2022-12-12 13:54 UTC, nikitapt63 requested changes

2022-12-12 13:54 UTC, nikitapt63 commented on DZ_13_Soda.py
> +            return print("Regular sparkling water")
нет инициализатора

2022-12-12 13:54 UTC, nikitapt63 commented on DZ_13_circle.py
> +    global perimeter_circle_calculation
зачем global?

2022-12-12 16:55 UTC, Ruslan080183 commented on DZ_13_circle.py
> +    global perimeter_circle_calculation
для импорта в файл DZ_13_view

2022-12-12 16:56 UTC, Ruslan080183 commented on DZ_13_Soda.py
> +            return print("Regular sparkling water")
Замечание понял, доработаю.

2022-12-15 19:02 UTC, nikitapt63 requested changes

2022-12-15 19:02 UTC, nikitapt63 commented on DZ_13_Soda1.py
> +        else:
Если при создании экземпляра я укажу, что добавил что-то кроме ["Coca - cola", "Sprite", "Fanta", "Cherry"]. Оно будет работать?

2022-12-15 19:05 UTC, Ruslan080183 commented on DZ_13_Soda1.py
> +        else:
Понял, сделаю любая добавка, а не из списка, иначе просто без добавки

2022-12-16 11:16 UTC, nikitapt63 approved these changes

2022-12-16 16:08 UTC, merged