DZ_14.Working with Python Class Methods
Ruslan080183/Training pull request #12
Opened 2022-12-18 19:26 UTC by Ruslan080183

2022-12-19 05:56 UTC, nikitapt63 requested changes

2022-12-19 05:56 UTC, nikitapt63 commented on DZ_14/car_opel.py
> +      print("This car brand Opel")
Проверь работает ли счетчик тут правильно?

2022-12-19 15:47 UTC, Ruslan080183 commented on DZ_14/car_opel.py
> +      print("This car brand Opel")
Работает

2022-12-21 05:26 UTC, nikitapt63 approved these changes

2022-12-21 10:36 UTC, merged