DZ_10.Multiple class inheritance
Ruslan080183/Training pull request #9
Opened 2022-11-30 18:49 UTC by Ruslan080183

2022-11-30 20:14 UTC, nikitapt63 reviewed
Отлично, есть пару логических ошибок, на занятии разберем)
За актуальную тему - плюс!)

2022-12-01 05:12 UTC, Ruslan080183 commented
> 

Спасибо

2022-12-04 12:23 UTC, nikitapt63 requested changes

2022-12-04 12:23 UTC, nikitapt63 commented on DZ_11.py
> +        self.c = c
У тебя здесь три атрибута, по условию сказано, что атрибут один - лист, состоящий из трех элементов

2022-12-04 17:50 UTC, nikitapt63 approved these changes

2022-12-04 17:50 UTC, merged